'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''RSSDisplay class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class RSSDisplay

    '''<summary>
    '''btnRefreshNews control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshNews As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSource As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lstRSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstRSS As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''xmlSourceRSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xmlSourceRSS As Global.System.Web.UI.WebControls.XmlDataSource

    '''<summary>
    '''pnlRSSFeedEditor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRSSFeedEditor As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''TblRSSFeed_Editor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TblRSSFeed_Editor1 As Global.HomePage2.tblRSSFeed_Editor
End Class
