'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace au.com.quantumsoftware.www
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WorldTimeWebServiceSoap", [Namespace]:="http://www.quantumsoftware.com.au/WorldTimeWebService/")>  _
    Public Class WorldTimeWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://www.quantumsoftware.com.au/WorldTimeWebService/WorldTimeWebService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.quantumsoftware.com.au/WorldTimeWebService/GetTimeZones", RequestNamespace:="http://www.quantumsoftware.com.au/WorldTimeWebService/", ResponseNamespace:="http://www.quantumsoftware.com.au/WorldTimeWebService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTimeZones() As TimeZoneInfo()
            Dim results() As Object = Me.Invoke("GetTimeZones", New Object(-1) {})
            Return CType(results(0),TimeZoneInfo())
        End Function
        
        '<remarks/>
        Public Function BeginGetTimeZones(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTimeZones", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetTimeZones(ByVal asyncResult As System.IAsyncResult) As TimeZoneInfo()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),TimeZoneInfo())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.quantumsoftware.com.au/WorldTimeWebService/GetTimeZoneInfo", RequestNamespace:="http://www.quantumsoftware.com.au/WorldTimeWebService/", ResponseNamespace:="http://www.quantumsoftware.com.au/WorldTimeWebService/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTimeZoneInfo(ByVal timeZoneName As String) As TimeZoneInfo
            Dim results() As Object = Me.Invoke("GetTimeZoneInfo", New Object() {timeZoneName})
            Return CType(results(0),TimeZoneInfo)
        End Function
        
        '<remarks/>
        Public Function BeginGetTimeZoneInfo(ByVal timeZoneName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTimeZoneInfo", New Object() {timeZoneName}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetTimeZoneInfo(ByVal asyncResult As System.IAsyncResult) As TimeZoneInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),TimeZoneInfo)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.quantumsoftware.com.au/WorldTimeWebService/")>  _
    Public Class TimeZoneInfo
        
        '<remarks/>
        Public Name As String
        
        '<remarks/>
        Public DaylightName As String
        
        '<remarks/>
        Public StandardName As String
        
        '<remarks/>
        Public DisplayName As String
        
        '<remarks/>
        Public UtcOffsetTicks As Long
        
        '<remarks/>
        Public CurrentTimeTicks As Long
        
        '<remarks/>
        Public IsInDaylightSaving As Boolean
    End Class
End Namespace
