'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
'
Namespace com.mastercsharp.www
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="World Time ServiceSoap", [Namespace]:="MasterCSharp.WebServices")>  _
    Public Class WorldTimeService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://www.mastercsharp.com/live/TimeService/TimeService.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("MasterCSharp.WebServices/AddUser", RequestNamespace:="MasterCSharp.WebServices", ResponseNamespace:="MasterCSharp.WebServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddUser(ByVal email As String, ByVal password As String) As String
            Dim results() As Object = Me.Invoke("AddUser", New Object() {email, password})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginAddUser(ByVal email As String, ByVal password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddUser", New Object() {email, password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddUser(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("MasterCSharp.WebServices/GetLocationList", RequestNamespace:="MasterCSharp.WebServices", ResponseNamespace:="MasterCSharp.WebServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLocationList() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetLocationList", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetLocationList(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetLocationList", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetLocationList(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("MasterCSharp.WebServices/GetUserClocks", RequestNamespace:="MasterCSharp.WebServices", ResponseNamespace:="MasterCSharp.WebServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserClocks(ByVal email As String, ByVal password As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetUserClocks", New Object() {email, password})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginGetUserClocks(ByVal email As String, ByVal password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetUserClocks", New Object() {email, password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetUserClocks(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("MasterCSharp.WebServices/UpdateUserClocks", RequestNamespace:="MasterCSharp.WebServices", ResponseNamespace:="MasterCSharp.WebServices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateUserClocks(ByVal email As String, ByVal password As String, ByVal locations() As Integer) As String
            Dim results() As Object = Me.Invoke("UpdateUserClocks", New Object() {email, password, locations})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateUserClocks(ByVal email As String, ByVal password As String, ByVal locations() As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateUserClocks", New Object() {email, password, locations}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateUserClocks(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
